name: Publish Python Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    environment: Twine Environment # Specifies the environment to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to Custom PyPI Repository
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }} # From the Twine Environment secrets
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }} # From the Twine Environment secrets
        run: |
          twine upload --repository-url http://43.204.15.2:9090/mmdev/mm_repo --skip-existing dist/*.whl

      - name: Test package installation from custom repository
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }} # From the Twine Environment secrets
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }} # From the Twine Environment secrets
        run: |
          pip install --trusted-host 43.204.15.2 --extra-index-url http://43.204.15.2:9090/mmdev/mm_repo --no-deps mm-browser-use
